### ISSUE TITLE
Issue while submitting to store

### ISSUE THREAD

**Issue by vikram1234** [fastlane/examples#14]
[04:17:13]: [Transporter]: INFO: The package: /tmp/1084529916.itmsp has been successfully uploaded.
[04:17:14](------------------------------------------------------------------------------------------------------): iTunes Transporter successfully finished its job
[04:17:14](------------------------------------------------------------------------------------------------------): [Transporter]: DBG-X: Returning 0

[04:17:14](------------------------------------------------------------------------------------------------------): Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.

[04:17:14](------------------------------------------------------------------------------------------------------): Finished the upload to iTunes Connect
[04:17:15]: Selecting the latest build...
[04:17:16]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:17:48]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:18:20]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:18:51]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:19:22]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:19:54]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:20:26]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:20:57]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:21:29]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:22:01]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:22:32]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:22:32]: 
[04:22:32]: You can tweet: "iTunes Connect #iosprocessingtime 5 minutes"
[04:23:04]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:23:04]: 
[04:23:04]: You can tweet: "iTunes Connect #iosprocessingtime 6 minutes"
[04:23:35]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:23:35]: 
[04:23:35]: You can tweet: "iTunes Connect #iosprocessingtime 6 minutes"
[04:24:16]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:24:16]: 
[04:24:16]: You can tweet: "iTunes Connect #iosprocessingtime 7 minutes"
[04:24:48]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:24:48]: 
[04:24:48]: You can tweet: "iTunes Connect #iosprocessingtime 8 minutes"
[04:25:23]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:25:23]: 
[04:25:23]: You can tweet: "iTunes Connect #iosprocessingtime 8 minutes"
[04:25:55]: Waiting iTunes Connect processing for build 1.0 (1.0)... this might take a while...
[04:25:55]: 
[04:25:55]: You can tweet: "iTunes Connect #iosprocessingtime 9 minutes"
[04:26:27]: Selecting build 1.0 (1.0)...
[04:26:28]: Successfully selected build
[04:26:28]: Submitting the app for review...
[04:26:31]: Variable Dump:
[04:26:31]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios appstore", :CERT_FILE_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/V52DKXD3X5.cer", :CERT_CERTIFICATE_ID=>"V52DKXD3X5", :SIGH_PROFILE_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/AppStore_com.proappslive.proappstest.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/AppStore_com.proappslive.proappstest.mobileprovision"], :SIGH_UDID=>"4c3eb709-c79e-4f84-9049-04eaecd1ee41", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/proapps.ipa", :DSYM_OUTPUT_PATH=>"/Users/viki/Desktop/fastlane/apps/proapps/platforms/ios/util/proapps.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/viki/Library/Developer/Xcode/Archives/2016-02-26/proapps 2016-02-26 04.13.27.xcarchive"}
[04:26:31]: Re-validating version produced errors.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cert                                | 4           |
| 4    | sigh                                | 6           |
| 5    | pem                                 | 1           |
| 6    | update_project_provisioning         | 11          |
| 7    | gym                                 | 71          |
| 8    | deliver                             | 718         |
+------+-------------------------------------+-------------+

[04:26:32]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'baf21134185e391a2e55b74cf9207f9d'
The crash report has been stored locally '/tmp/sentry_baf21134185e391a2e55b74cf9207f9d.json'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/tunes_client.rb:207:in `handle_itc_response': [!] Re-validating version produced errors. (Spaceship::TunesClient::ITunesConnectError)
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/tunes_client.rb:683:in`send_app_submission'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.20.0/lib/spaceship/tunes/app_submission.rb:127:in `complete!'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/submit_for_review.rb:25:in`submit!'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:87:in `submit_for_review'
    from /Library/Ruby/Gems/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:30:in`run'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/actions/deliver.rb:18:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:143:in`block (2 levels) in execute_action'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:129:in`block in execute_action'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in `chdir'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:128:in`execute_action'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/fast_file.rb:149:in `method_missing'
    from Fastfile:126:in`block (2 levels) in parsing_binding'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/lane.rb:36:in`call'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:52:in `block in execute'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in`chdir'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/runner.rb:46:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/lane_manager.rb:46:in`cruise_lane'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/lib/fastlane/command_line_handler.rb:30:in `handle'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:38:in`block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in`call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in`run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.8/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in`run!'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:156:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.63.1/bin/fastlane:162:in`<top (required)>'
    from /usr/local/bin/fastlane:23:in `load'
    from /usr/local/bin/fastlane:23:in`<main>'

**Comment by vpolouchkine** [comment]
Can you please open the issue under `deliver`? (https://github.com/fastlane/deliver/issues)
